config/routes.rb
Rails.application.routes.draw do
  root 'traps#index'

  controller :admin do
    get 'admin' => :index
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'admin' => :create
    post 'users/new' => :create
    delete 'logout' => :destroy
  end

  controller :traps do
    get 'traps' => :index
    match 'traps/:trap_name' => :capture_request, via: :all
    match 'traps/:trap_name/requests' => :show, as: :trap, via: :get
    delete 'traps/:trap_name/:id' => :destroy
    patch 'traps/:trap_name/requests' => :update
    put 'traps/:trap_name/requests' => :update
  end

  controller :requests do
    match 'traps/:trap_name/requests/:id' => 'requests#show', as: :requests, via: :get
    delete 'traps/:trap_name/requests/:id' => :destroy
  end

  resources :users

end

app/models/trap.rb
class Trap < ActiveRecord::Base
  validate presence: true
  has_many :requests, dependent: :destroy
end

app/controllers/traps_controller.rb
class TrapsController < ApplicationController
  skip_before_action :authorize, only: :capture_request
  #
  # GET /traps
  #
  def index
    @traps = Trap.all.order(created_at: :desc)
    respond_to do |format|
      format.html
    end
  end
  #
  # GET /traps/trap_name/requests
  #
  def show
    name = flash[:new_trap_name]
    @trap = Trap.find_by("name = ?", params[:trap_name]) || Trap.find_by("name = ?", name )
    if @trap
      @requests = @trap.requests.order(created_at: :desc)
    else
      respond_to do |format|
        format.html { redirect_to traps_path, notice: "No traps #{params[:trap_name]} found."}
      end
    end
  end
  #
  # PATCH/PUT /traps/trap_name/requests
  #
  def update
    @trap = Trap.find_by("id = ?", params[:trap_name])
    current_trap_name = @trap.name
    respond_to do |format|
      if @trap.update(trap_params)
        format.html { redirect_to trap_path(@trap.name), notice: "Trap #{current_trap_name} was successfully updated.", flash: {new_trap_name: trap_params} }
        format.json { render :show, status: :ok, location: @trap }
      else
        format.html { redirect_to trap_path(@trap.name), notice: 'Trap wasn\'t updated' }
        format.json { render json: @trap.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # DELETE /traps/trap_name/1
  #
  def destroy
    Trap.find_by(name: params[:trap_name]).destroy
    respond_to do |format|
      format.html { redirect_to traps_path, notice: 'Trap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #
  # Capture traps/request and save to database action.
  #
  def capture_request
    already_exist = false
    already_exist = true if Trap.find_by(name: params[:trap_name])
    @trap = Trap.find_or_create_by(name: params[:trap_name])
    header = Hash.new
    request.headers.each { |key, value| header[key] = value.to_s unless value.is_a?(Hash) }
    @req = create_request(@trap, request.remote_ip, request.method, request.scheme, request.query_string,
                         request.query_parameters, request.cookies, header)

    respond_to do |format|
      if @trap
        WebsocketRails[:trap].trigger 'new', render_to_string(partial: 'traps/trap') unless already_exist
        WebsocketRails[:request].trigger 'new', render_to_string(partial: 'traps/request') if @req
        format.html { redirect_to traps_path, notice: 'Request was successfully captured.'}
      else
        format.html { redirect_to traps_path, notice: 'Request wasn\'t captured.'}
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def trap_params
    params.require(:trap).permit(:name)
  end

  def create_request (trap, remote_ip, request_method, scheme, query_string, query_params, cookies, headers)
    trap.requests.create(remote_ip: remote_ip, request_method: request_method,
                         scheme: scheme, query_string: query_string,
                         query_params: query_params, cookies: cookies, headers: headers)
  end
end

app/helpers/traps_helper.rb
module TrapsHelper
end

app/views/traps/_request.html.erb
<tr>
  <td> 1 </td>
  <td><%= @req.created_at.strftime("%F %T") %></td>
  <td><%= @req.remote_ip %></td>
  <td><%= @req.request_method %></td>
  <td><%= link_to 'Details', requests_path(@trap.name, @req) %></td>
</tr>
<script type="text/javascript">
    $('tr').mouseover(function() {
        $(this).addClass('focused');
    });
    $('tr').mouseleave(function() {
        $(this).removeClass('focused');
    });
</script>

app/views/traps/_trap.html.erb
<tr>
  <td> 1 </td>
  <td><%= @trap.name %></td>
  <td><%= @trap.created_at.strftime("%F %T") %></td>
  <td><%= link_to 'Go to', trap_path(@trap.name) %></td>
</tr>
<script type="text/javascript">
    $('tr').mouseover(function() {
        $(this).addClass('focused');
    });
    $('tr').mouseleave(function() {
        $(this).removeClass('focused');
    });
</script>

app/views/traps/index.html.erb
<h1 class="table-title">Trap list</h1>
<div class="container">
  <table class="trap-list listing-table">
    <thead>
    <tr>
      <td>#</td>
      <td>Trap name</td>
      <td>Date</td>
      <td></td>
    </tr>
    </thead>
    <tbody>
    <% @traps.each_with_index do |trap, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= trap.name %></td>
        <td><%= trap.created_at.strftime("%F %T") %></td>
        <td><%= link_to 'Go to', trap_path(trap.name) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/traps/index.js.erb
/**
 * Created by hp on 19.02.15.
 */
var dispatcher = new WebSocketRails('localhost:3000/websocket');
var channel = dispatcher.subscribe('traps');
channel.bind('new', function() {
    $('.container').html('traps/_trap.html');
});

app/views/traps/show.html.erb
<h1 class="table-title "><%= @trap.name %></h1>
<div class="listing-manipulation">
  <div>
    <%= link_to 'Delete', trap_path(@trap.name), method: :delete %>
  </div>
  <div class="edit-btn">
    Edit
  </div>
  <div>
    <%= link_to 'Back', traps_path %>
  </div>
</div>
<div class="edit-form">
  <%= form_for(@trap) do |f| %>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.submit 'Rename' %></p>
  <% end %>
</div>
<div class="container">
    <table class="request-list listing-table">
      <thead>
      <tr>
        <td>#</td>
        <td>Created at</td>
        <td>Remote ip</td>
        <td>Request method</td>
        <td></td>
      </tr>
      </thead>
      <tbody>
      <% @requests.each_with_index do |request, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= request.created_at.strftime("%F %T") %></td>
            <td><%= request.remote_ip %></td>
            <td><%= request.request_method %></td>
            <td><%= link_to 'Details', requests_path(@trap.name, request) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>